CREATE DATABASE my_database;

CREATE TABLE "videos" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255),
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "frames" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "video_id" int,
  "frame_number" int,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "frame_data" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "frame_id" int,
  "class" int,
  "x" float,
  "y" float,
  "width" float,
  "height" float,
  "confidence" float
);

ALTER TABLE "frames" ADD FOREIGN KEY ("video_id") REFERENCES "videos" ("id");

ALTER TABLE "frame_data" ADD FOREIGN KEY ("frame_id") REFERENCES "frames" ("id");

CREATE INDEX idx_frames_video_id ON frames(video_id);
CREATE INDEX idx_frame_data_frame_id ON frame_data(frame_id);