apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80      # Puerto externo (HTTP)
      targetPort: 3000  # Puerto donde escucha tu backend en el contenedor
  type: LoadBalancer