apiVersion: apps/v1
kind: Deployment
metadata:
  name: process-videos
spec:
  replicas: 0
  selector:
    matchLabels:
      app: process-videos
  template:
    metadata:
      labels:
        app: process-videos
    spec:
      containers:
      - name: process-videos
        image: 140023402256.dkr.ecr.us-east-1.amazonaws.com/yoloprocessor:latest
        env:
        - name: DB_NAME
          value: "viratdata"
        - name: DB_USER
          value: "root"
        - name: DB_PASSWORD
          value: "root1997+"
        - name: DB_HOST
          value: "dbcluster.c9yee2e0yxjp.us-east-1.rds.amazonaws.com"
        - name: DB_PORT
          value: "5432"
        - name: S3_BUCKET
          value: "viratvideos"
        - name: S3_REGION
          value: "us-east-1"
        resources:
          requests:
            cpu: 1          # Reserva 0.5 núcleos como mínimo
            memory: 2Gi        # Reserva 1 GiB de memoria como mínimo
          limits:
            cpu: 1          # Límite máximo de 1 núcleo
            memory: 10Gi        # Límite máximo de 2 GiB de memoria