apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30080 # Puedes definir un puerto o dejar que Kubernetes lo asigne
  type: NodePort