apiVersion: v1
kind: PersistentVolume
metadata:
  name: video-storage
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/Users/edward/Desktop/Cloud/viratvideos"  
  storageClassName: standard  