apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: video-storage-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
  volumeName: video-storage 